### ISSUE TITLE
Not working with React Navigation without enabling Remote Debug Debugging

### ISSUE THREAD

**Issue by neyosoft** [IjzerenHein/react-native-magic-move#14] opened 2019-06-02 22:28 UTC
### Expected behaviour

I expect the shared  transition to work without enabling Remote JS Debugging

### Show Actual behavior
The shared transition doesn't work after navigating to another route where I have **Magic.View** component with the same id on the current screen am navigation from.
I keep getting an error: "**parameter must be a descendant of this view**". But if I enable Remote JS Debugging. it will work as expected.

### I'm seeing this behavior on

- Device: (e.g. Android 7.1, Honor 5X, Android 6 Infinix HOT Note)
- Routing/transition library: (e.g. react-navigation v3.11.0)
- React-native version: v0.59.8
- react-native-magic-move version: v^0.6.2

### Provide the code

if the Remote JS debugging is enabled. Everything works fine and I don't see any console error message. But when I stop Remote JS Debugging. I got back the same error when navigation to the new screen **parameter must be a descendant of this view**

**Comment by IjzerenHein** [comment] 2019-06-05 09:34
Alright, thanks for reporting this, I'm going to take a look 👍

**Comment by rgommezz** [comment] 2019-07-25 14:52
Hey @IjzerenHein, first of all lemme tell you that this library is awesome, I've seen your talk and tinkered with the examples and the animations are delightful, well done! 🥇

However, I am experiencing the same issue as @neyosoft. 

I've done a little research about it to find a minimum reproduction case. 

My findings are quite interesting. The problem arises when you have on your screen some array structure inside render. Let me shed some light.

Having wrapped your entire application with `Magic.Provider` and imported 'react-navigation-magic-move' on the entry point, imagine the below screen with some `MagicMove` view:

```jsx
        <MagicMove.Scene>
            <MagicMove.View
                id={shared}
                style={styles.role}
            >
                <Avatar.Image
                    size={AVATAR_SIZE}
                    source={{uri: imageSrc}}
                />
                <Title>{name}</Title>
                <Paragraph>{description}</Paragraph>
            </MagicMove.View>
        </MagicMove.Scene>

```

That works as expected, no issues.

However, changing slightly the structure as below *produces the crash*:

```jsx
        <MagicMove.Scene>
            {
                [
                    <MagicMove.View
                        id={shared}
                        style={styles.role}
                    >
                        <Avatar.Image
                            size={AVATAR_SIZE}
                            source={{uri: imageSrc}}
                        />
                        <Title>{name}</Title>
                        <Paragraph>{role}</Paragraph>
                    </MagicMove.View>
                ]
            }
        </MagicMove.Scene>

```

Array structures are the atomic units for both `ScrollView` and `FlatList` components, so as long as you have one of those components, you'll likely run into a crash with MagicMove, like:


```jsx
        <MagicMove.Scene>
            {data.map(item => (
                <MagicMove.View key={item.id} id={id} style={styles.role}>
                    <Avatar.Image
                        size={AVATAR_SIZE}
                        source={{uri: item.imageUri}}
                    />
                    <Title>{item.name}</Title>
                    <Paragraph>{item.role}</Paragraph>
                </MagicMove.View>
            ))}
        </MagicMove.Scene>

```

Now, having said that, I have no idea why when you run the JS on chrome V8 (debugging mode on), you don't run into this issue as opposed to JSCore 🤔.

Babel React preset (included in metro) will just create an array of React.createElement calls as expected. Any ideas?

In the meantime, I am gonna try to integrate the new engine `Hermes` with my app and see what happens, haha

**Comment by IjzerenHein** [comment] 2019-07-29 09:15
Hi, thanks for the extensive bug-report @rgommezz, that's awesome!
I'm quite busy at the moment but I'll try to take a closer look at it later this week.
cheers, Hein

**Comment by IjzerenHein** [comment] 2019-07-31 12:47
Hi, thanks again for the great feedback and trouble-shooting so far, this really helps a lot! I've begun looking into the problem and will share any updates here. So far, I've been unable to reproduce the problem but I'll keep trying.
Just curious, are you using `react-native-screens`?

**Comment by IjzerenHein** [comment] 2019-07-31 13:41
Hi, I've managed to repro the problem by updating my example app to use the latest react-navigation. Stay tuned..

**Comment by rgommezz** [comment] 2019-07-31 16:45
Great news @IjzerenHein!

Just in case it's useful for you, I have `react-native-screens` turned off on Android (for a different reason).

**Comment by IjzerenHein** [comment] 2019-08-01 12:01
Okay thanks for the info.

Well I've discovered a thing or two. It seems that the problem occurs when magic-move can't measure the layout within the set timeouts. The code retries to measure a couple times and each time a new timeout is started. It's possible that on debug builds (or when running the debugger) this behaves differently, timing wise, due to other things happening as well on the main UI thread.

The measure retry code in Android is not solid enough and can't handle it when layouting takes too long. This needs to be fixed. I'll need to take a closer look on how to solve that as I'm also not a Java/Android expert :)

**Comment by IjzerenHein** [comment] 2019-08-03 10:33
Hi. I've released a new version in which this problem should be fixed. Could you install it and let me know whether that fixes the problem for you?
You can install it via `react-native-magic-move@next`.
https://github.com/IjzerenHein/react-native-magic-move/releases/tag/v0.6.4

When confirmed I will release it officially.
cheers

**Comment by rgommezz** [comment] 2019-08-03 10:59
Excellent! I'll do so this weekend. Will keep you updated

**Comment by rgommezz** [comment] 2019-08-04 23:27
I've tested the new version and seems to work like a charm! 🚀

Out of curiosity, how did you end up fixing the problem?

Feel free to close this issue.

Thanks very much, fantastic work!

![](https://media.giphy.com/media/ar4x1w44umngk/giphy-downsized.gif)

**Comment by IjzerenHein** [comment] 2019-08-06 08:02
Awesome, glad to hear that it solved the problem for you! :D :D

Well there are two things that I managed to fix. The first thing was the measure-retry mechanism I mentioned earlier. It tried a max of 3 times to measure and when that didn't work it could crash. That mechanism has been rewritten and it now retries up to a 100 times (max 800ms, just to be sure). Usually it gets it after 4 or 5 retries though. I also added some warnings to that mechanism when measuring takes longer than expected.

The second issue I found was that even though the measure had succeeded, it would still throw **parameter must be a descendant of this view** very occasionally when calling `offsetDescendantRectToMyCoords`. This was very strange as the previous call to measure had succeeded. I do have a theory about this and in order to understand that you need to understand what the purpose of `offsetDescendantRectToMyCoords` was here. That call basically did a second measure, but that measure took into account what the scroll-offset was (which the initial one didn't). The initial `uiManager.measureLayout` call measured using the RN shadow view-hierarchy and `offsetDescendantRectToMyCoords` measured using the actual views in the Android view hierarchy. It might have been possible that even though the shadow view-hierarchy was up to date, the actual views, yet weren't. And this caused that call to fail sometimes when a new view was mounted and needed to be added to the view-hierarchy. I then decided to change that part and try to detect the scroll-offset in a safer manor.

**Comment by IjzerenHein** [comment] 2019-08-06 08:07
Released as https://github.com/IjzerenHein/react-native-magic-move/releases/tag/v0.6.5

**Comment by rgommezz** [comment] 2019-08-08 16:01
Thanks very much for the explanation and fix, it makes sense! 🎉

**Closed** 2019-08-12 11:37 UTC
Labels: android, bug
