### ISSUE TITLE
[MagicMove] Failed to measure undefined

### ISSUE THREAD

**Issue by Batuhan-Akkaya** [IjzerenHein/react-native-magic-move#4] opened 2019-01-15 19:41 UTC
Platform: Android
error: [MagicMove] Failed to measure undefined , Cannot read property 'measureLayout' of null
work on ios.

**Comment by IjzerenHein** [comment] 2019-01-15 20:33
Hi, please provide more information so I can reproduce this problem. For instance, a snippet of the to- and from screens. I cannot reproduce the problem with so little information.

**Comment by Batuhan-Akkaya** [comment] 2019-01-15 20:47
i updated version 3 to 4 and i installed react-navigation-magic-move so i get this error on android. I've tried a lot of ways but couldn't figure it out.
it works very well on Ios.

**Comment by IjzerenHein** [comment] 2019-01-15 20:49
What do you mean by updated version 3 to 4?

**Comment by Batuhan-Akkaya** [comment] 2019-01-15 20:55
"react-native-magic-move": "0.3.0" => "0.4.0" in package json

**Comment by IjzerenHein** [comment] 2019-01-16 05:58
Did it work correctly for you with "0.3" on Android?

**Comment by Batuhan-Akkaya** [comment] 2019-01-16 07:56
yes this my app, used 0.3
https://itunes.apple.com/ky/app/honestly/id1447775146
https://play.google.com/store/apps/details?id=com.batuhanakkaya.honestly

**Comment by IjzerenHein** [comment] 2019-01-16 17:05
Ok I've installed the app on my iPhone. In the launch screen, when I click "Login" I see a move animation. Is that the animation that is causing a crash on Android?

**Comment by Batuhan-Akkaya** [comment] 2019-01-16 17:20
no works because this 0.3 when i update to 0.4 android crash

**Comment by IjzerenHein** [comment] 2019-01-16 18:17
Could you try to disable the react-navigation-magic-move import. Does it still crash then?

**Comment by Batuhan-Akkaya** [comment] 2019-01-16 18:21
i tried all ways but not worked :(

**Comment by IjzerenHein** [comment] 2019-01-16 18:41
Dang, that sucks. I really need to be able to reproduce the problem in order to understand what's going on. Can you share a simple app (code/gist) that causes the problem for you?

**Comment by IjzerenHein** [comment] 2019-02-07 15:30
Hi, is this still in issue with v0.5.0?

**Comment by Batuhan-Akkaya** [comment] 2019-02-07 16:33
i didn't try yet. I will try. Tnx

**Comment by IjzerenHein** [comment] 2019-02-28 08:56
Can I close this?

**Comment by IjzerenHein** [comment] 2019-08-03 10:35
Closing due to inactivity

**Closed by IjzerenHein** 2019-08-03 10:35 UTC
Labels: android, information requested
